### ISSUE TITLE
MSI installer, Windows 10 1809: ImportError: DLL load failed

### ISSUE THREAD

**Issue by licaon-kter** [jeromerobert/pdfarranger#122] opened 2019-11-06 11:55 UTC
1.3.1 Windows 10 1809 64bit

![pdfarragerissue](https://user-images.githubusercontent.com/2282799/68296359-52098b00-008c-11ea-9c13-3de47fb7cb47.JPG)

**Comment by jeromerobert** [comment] 2019-11-06 14:09
Is it with the `.msi` installer or the `.zip` archive ?

**Comment by licaon-kter** [comment] 2019-11-06 14:43
Installer .msi

**Comment by jeromerobert** [comment] 2019-11-07 04:46
Sorry but I'm enable to reproduce the issue. Could you try the `.zip` ?

The error message tend to say that a GTK DLL is missing from the installer (or has been removed by an antivirus after the installation). We could find that file by doing the following:
* Run `cmd.exe`
* Run `C:\Users\jerome>dir /s "c:\Program Files\pdfarranger" > c:\Users\jerome\Desktop\
pdfarranger.log` (adapt both path to your case).
* Attach the `pdfarranger.log` to this issue (or send it to me by email).

**Comment by jgvictores** [comment] 2019-11-07 09:40
Just ran into exact same issue as the description image above, via `pdfarranger-1.3.1-mingw.msi`. Here's the log you mention, hope it helps: [pdfarranger.log](https://github.com/jeromerobert/pdfarranger/files/3818842/pdfarranger.log)

PS: Yes, I'm able to run the program contained in `pdfarranger-1.3.1-mingw.zip`.

**Comment by jeromerobert** [comment] 2019-11-07 16:00
No differences at all with my installations on Windows 7 or Windows 10 1709, so it's not about a missing file. [Procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) could be used to find what's going on. Unfortunately I won't have access to a 1809 installation before the next month. In the meanwhile, it would be nice if someone who knows how to use Procmon, could have a look to that issue. Else we'll wait that I get my Windows upgrade.

**Comment by jeromerobert** [comment] 2019-11-10 14:59
I managed to find a Windows 10 1809 64bit box and tested the MSI installer. I was not able to reproduce that issue.

**Comment by jgvictores** [comment] 2019-11-11 10:42
Hi! I tried `procmon` (never have heard of it before, seems useful!), ran the `.msi`-installed program to get the crash, and applied filters until all entries were `pdfarranfger`-related. I exported the results to `.PML`, `.CSV` and `.XML` with all options available (including some trace-back option taht said it would do it slower).

Not sure if these files contain any sensitive information. @jeromerobert To where could I email them for you?

**Comment by jeromerobert** [comment] 2019-11-11 12:23
thanks ! you can send it to jeromerobert@gmx.com

**Comment by jgvictores** [comment] 2019-11-11 13:35
Ok! The `.XML` is over `70MB`, so I shared the folder with the 3 files to that email via Dropbox. Hope it reaches you and is helpful!

**Comment by jeromerobert** [comment] 2019-11-12 21:54
I see that pdfarranger is loading `C:\Program Files\Intel\WiFi\bin\zlib1.dll` instead of it's own `zlib1.dll`. Could you try to run pdfarranger from `cmd.exe` after cleaning the `PATH` variable with:
`set PATH=C:\Windows\system32;C:\Windows` ?

Also the first file which is loaded on my computer and not loaded on yours is `C:\Program Files\pdfarranger\lib\gi\_gi_cairo-cpython-37m.dll`, but I no idea why.

**Comment by jgvictores** [comment] 2019-11-14 11:57
Hi! Sorry, I am travelling and do not have access to the machine (desktop) on which I've been testing this until Sunday/Monday. In fact, I've installed the `.msi` on another machine (laptop ^^) and it works out of the box. This could support the hypothesis regarding a "shadowing" effect of the `PATH` environment variable on specific machines. I'll keep you updated once I'm back for testing!

**Comment by jgvictores** [comment] 2019-11-18 12:07
I confirm that on the machine where I had this error, the culprit was `C:\Program Files\Intel\WiFi\bin` in the `PATH`.  Removing the entry solved the problem (which was not even present when launching from `cmd.exe`).

@jeromerobert It's up to you how you decide to treat/classify this issue, as I'm neither the owner of the repository nor the author of the original post. On my side, thanks a lot for your help and your time!

**Comment by jeromerobert** [comment] 2019-12-21 18:09
No longer active. Closing.

**Closed by jeromerobert** 2019-12-21 18:09 UTC
