### ISSUE TITLE
The metadata field /PTEX.Fullbanner with value 'pikepdf.String("This is pdfTeX, Version 3.14159265...

### ISSUE THREAD

**Issue by kbengs** [jeromerobert/pdfarranger#217] opened 2020-07-01 15:54 UTC
When I try to export pages from this file:
https://readthedocs.org/projects/pikepdf/downloads/pdf/latest/

This message will show up:
![Error](https://user-images.githubusercontent.com/60842129/86262193-3b3e1880-bbc8-11ea-9850-064dda1a1829.png)

Pikepdf version 1.16.1. Same also with version 1.14.0.

The exported pdf seems to be okay. If I try it a second time, it will show no error.

What to think about this?

**Comment by dreua** [comment] 2020-07-01 22:28
> The exported pdf seems to be okay. If I try it a second time, it will show no error.

This is what I would expect, pikepdf informs you that it can't store those two metadata-fields but the rest of the file should be okay.

**Comment by kbengs** [comment] 2020-07-04 14:51
Ok. I tried to open this and save on Windows 10 and there a dialog say " 'NoneType' object has no attribute 'write' " and the file is not saved. If I try to save again, same will happen. If I try once more, then it will be saved.

**Comment by jeromerobert** [comment] 2020-07-04 16:09
Indeed. Thank you. I cannot reproduce that bug on Linux. I tried to upgrade to pikepdf 1.6.1 to get https://github.com/pikepdf/pikepdf/commit/fe807802da41b8ab3fb9d4977102fdf84f55acec but I still get the same error. I'm still investigating.

**Comment by jeromerobert** [comment] 2020-07-04 16:55
Fixed in 1.6.0rc2.

**Closed** 2020-07-10 01:34 UTC
