### ISSUE TITLE
setuptools install data files in site-packages instead of /prefix/share/pdfarranger

### ISSUE THREAD

**Issue by oz123** [jeromerobert/pdfarranger#90] opened 2019-07-06 20:35 UTC
The logic implemented to find the UI files is failing if I install the package directly to the system with `python setup.py install` (works fine though in virtual env).
```
$ sudo python3 setup.py install
running install
running bdist_egg
running egg_info
creating pdfarranger.egg-info
writing pdfarranger.egg-info/PKG-INFO
writing dependency_links to pdfarranger.egg-info/dependency_links.txt
writing entry points to pdfarranger.egg-info/entry_points.txt
writing requirements to pdfarranger.egg-info/requires.txt
writing top-level names to pdfarranger.egg-info/top_level.txt
writing manifest file 'pdfarranger.egg-info/SOURCES.txt'
writing manifest file 'pdfarranger.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/pdfarranger
copying pdfarranger/__main__.py -> build/lib/pdfarranger
copying pdfarranger/__init__.py -> build/lib/pdfarranger
copying pdfarranger/pdfarranger.py -> build/lib/pdfarranger
copying pdfarranger/iconview.py -> build/lib/pdfarranger
copying pdfarranger/undo.py -> build/lib/pdfarranger
copying pdfarranger/exporter.py -> build/lib/pdfarranger
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pdfarranger
copying build/lib/pdfarranger/__main__.py -> build/bdist.linux-x86_64/egg/pdfarranger
copying build/lib/pdfarranger/__init__.py -> build/bdist.linux-x86_64/egg/pdfarranger
copying build/lib/pdfarranger/pdfarranger.py -> build/bdist.linux-x86_64/egg/pdfarranger
copying build/lib/pdfarranger/iconview.py -> build/bdist.linux-x86_64/egg/pdfarranger
copying build/lib/pdfarranger/undo.py -> build/bdist.linux-x86_64/egg/pdfarranger
copying build/lib/pdfarranger/exporter.py -> build/bdist.linux-x86_64/egg/pdfarranger
byte-compiling build/bdist.linux-x86_64/egg/pdfarranger/__main__.py to __main__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pdfarranger/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pdfarranger/pdfarranger.py to pdfarranger.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pdfarranger/iconview.py to iconview.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pdfarranger/undo.py to undo.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pdfarranger/exporter.py to exporter.cpython-36.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/share
creating build/bdist.linux-x86_64/egg/share/applications
copying data/pdfarranger.desktop -> build/bdist.linux-x86_64/egg/share/applications
creating build/bdist.linux-x86_64/egg/share/pdfarranger
copying data/pdfarranger.ui -> build/bdist.linux-x86_64/egg/share/pdfarranger
creating build/bdist.linux-x86_64/egg/share/man
creating build/bdist.linux-x86_64/egg/share/man/man1
copying doc/pdfarranger.1 -> build/bdist.linux-x86_64/egg/share/man/man1
creating build/bdist.linux-x86_64/egg/share/metainfo
copying data/pdfarranger.appdata.xml -> build/bdist.linux-x86_64/egg/share/metainfo
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pdfarranger.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pdfarranger.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pdfarranger.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pdfarranger.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pdfarranger.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pdfarranger.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pdfarranger.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/pdfarranger-1.2.1-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pdfarranger-1.2.1-py3.6.egg
creating /usr/lib64/python3.6/site-packages/pdfarranger-1.2.1-py3.6.egg
Extracting pdfarranger-1.2.1-py3.6.egg to /usr/lib64/python3.6/site-packages
Adding pdfarranger 1.2.1 to easy-install.pth file
Installing pdfarranger script to /usr/bin

Installed /usr/lib64/python3.6/site-packages/pdfarranger-1.2.1-py3.6.egg
Processing dependencies for pdfarranger==1.2.1
Finished processing dependencies for pdfarranger==1.2.1


$ pdfarranger

(pdfarranger:13567): dbind-WARNING **: 22:32:03.629: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/pdfarranger-1.2.1-py3.6.egg/pdfarranger/pdfarranger.py", line 301, in do_activate
    self.uiXML.add_from_file(ui_path)
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/local/share/pdfarranger/pdfarranger.ui”: No such file or directory (4)
```

Would you accept a patch for fixing this problem? It's 2 lines of code ...

**Comment by jeromerobert** [comment] 2019-07-07 16:15
> Would you accept a patch for fixing this problem? It's 2 lines of code ...

Yes !

**Comment by jeromerobert** [comment] 2019-07-07 16:22
https://github.com/pypa/setuptools/issues/130

**Comment by jeromerobert** [comment] 2019-07-07 16:23
That one is nice too: https://github.com/kytos/kytos/issues/471

**Comment by jeromerobert** [comment] 2019-07-07 16:26
https://github.com/pypa/wheel/issues/92

**Comment by jeromerobert** [comment] 2019-07-07 16:27
@oz123 In your patch, please just be sure that `pip install` still work.

**Comment by dreua** [comment] 2019-07-08 08:12
I think me and possibly other downstream package maintainers will need to check if their package still works at build and runntime. If possible I would like to test it before it gets merged into master

**Comment by oz123** [comment] 2019-07-08 08:26
@dreua my patch is so minimal and does not change the behaviour for existing packages.

**Comment by jeromerobert** [comment] 2019-07-08 10:47
The problem is not that the .ui file is search in the wrong location, the problem is that it's installed in the wrong location. And the .ui file is not the only one. .desktop, .appdata.xml, man page etc... are also installed in the wrong location. Moreover the localization is not installed at all. 

`pkg_resources` is fine for python applications but pdfarranger is more GTK than python, and with GTK many things happen out side of `site-packages`.

The only good way to fix this issue is by hacking setuptools. May be it's possible by subclassing, but so far I didn't found how. That's why, so far we used pip install.

**Comment by oz123** [comment] 2019-07-08 12:45
This is has nothing todo with GTK application vs Python application. If your application uses setuptools, than you can for sure trust it to work in a virtualenv and when installed with a package manager.
pip install eventually uses `python setup.py install` under the hood.

**Comment by jeromerobert** [comment] 2019-07-08 16:08
Then how do you explain that `pip install` does work properly ?

**Comment by oz123** [comment] 2019-07-08 16:26
I believe it's calling also - setup.py build ...

**Comment by jeromerobert** [comment] 2019-07-08 16:29
Yes it does call `setup.py build` and not `setup.py install`.

**Comment by jeromerobert** [comment] 2020-08-15 16:09
This issue is probably tricky, more likely useless (as we use `pip install` and not `setup install`) and no one is working on it. So I'm closing that issue.

**Closed by jeromerobert** 2020-08-15 16:09 UTC
Labels: i wont do it will you
