### ISSUE TITLE
Error at save

### ISSUE THREAD

**Issue by lapega** [jeromerobert/pdfarranger#64] opened 2019-04-04 17:33 UTC
I'm trying to make a 4 pages pdf file.
When saving, it shows this error:

> Multiple definitions in dictionary at byte 0xd65 for key /x10

The file won't get saved.

![Captura de pantalla de 2019-04-04 14-32-39](https://user-images.githubusercontent.com/572502/55575972-82e4a480-56e6-11e9-8b2b-4129db9e8be0.png)

**Comment by jeromerobert** [comment] 2019-04-04 21:04
This is more likely an issue with one (or more) of the PDF file and/or a bug in PyPDF2. Could you isolate the culprit PDF and make it available somewhere ?

**Comment by lapega** [comment] 2019-04-05 12:16
Of course.

This one gives me problems:
[2_db.pdf](https://github.com/jeromerobert/pdfarranger/files/3047807/2_db.pdf)

**Comment by jeromerobert** [comment] 2019-04-05 14:11
This is related to #56 and https://github.com/mstamy2/PyPDF2/issues/244. If you use the current master branch you'll be able to save your files. The problem is that you'll get many warning messages and have to click for each of them. I'll try to improve that, so you get only one warning dialog box.

**Comment by jeromerobert** [comment] 2019-04-05 20:11
Done in 46f036e. Closing.

**Closed by jeromerobert** 2019-04-05 20:11 UTC
